config/routes.rb
Bloccit::Application.routes.draw do

  get "posts/index"

  get "comments/new"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: [:show, :index]

  resources :posts, only: [:index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :comments, only: [:create, :destroy, :show]
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
    end
  end

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :name, :public
  has_many :posts, dependent: :destroy

  scope :visible_to, lambda { |user| user ? scoped : where(public: true) }
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController

  def show
    @topic = Topic.find(params[:topic_id])
    authorize! :read, @topic, message: "You need to be signed-in to do that."
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize! :create, Post, message: "You need to be a member to create a post. Thanks!"
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params[:post])
    @post.topic = @topic
    authorize! :create, @post, message: "You need to be signed up to do that."
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :edit, @post, message: "You need to own the post to edit it."
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :update, @post, message: "You need to own the post to edit it."
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

   def destroy
     @topic = Topic.find(params[:topic_id])
     @post = Post.find(params[:id])

     title = @post.title
     authorize! :destroy, @post, message: "You need to own the post to delete it."
      if @post.destroy
        flash[:notice] = "\"#{title}\" was deleted successfully."
        redirect_to @topic
      else
        flash[:error] = "There was an error deleting the post."
        render :show
      end
    end  
  end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
  end

  def new
    @topic = Topic.new
    authorize! :create, @topic, message: "You need to be an admin to do that. Thanks!"
  end

  def show
    @topic = Topic.find(params[:id])
    authorize! :read, @topic, message: "You need to be signed-in to do that."
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to be an admin to do that. Thanks!"
  end

  def create
    @topic = Topic.new(params[:topic])
    authorize! :create, @topic, message: "You need to be an admin to do that. Thanks!"
    if @topic.save
      flash[:notice] = "Topic was saved successfully."
      redirect_to @topic
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to own a topic to update it. Thanks!"
    if @topic.update_attributes(params[:topic])
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again"
      render :edit
    end
  end
  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name
    authorize! :destory, @topic, message: "You need to own that topic to delete it."
    if @topic.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="span8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
    <%= will_paginate @topics %>
  </div>
  <div class="span4">
    <% if can? :create, Topic %>
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-large btn-block' %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="span-6">
    <p>Guidelines for new topics:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span-6">
    <%= form_for @topic, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :name, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :description, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :description, rows: 8 %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public topic
          <% end %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if can? :update, @topic %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-primary btn-mini' %>
<% end %>

<div class="row">
  <div class="span8">
    <p class="lead"><%= @topic.description %></p>
    

  <%= render @posts %>
   <%= will_paginate @posts %>
    
  </div>
  <div class="span4">
    <% if can? :create, Post %>
      <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-large btn-block' %>
    <% end %>
    <% if can? :destroy, @topic %>
    <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn-large btn-block btn-danger', confirm: 'Are you sure you want to delete this topic?' %> 
    <% end %>
  </div>
  </div>
</div>