config/routes.rb
Bloccit::Application.routes.draw do

  get "posts/index"

  get "comments/new"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: [:show, :index]

  resources :posts, only: [:index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :comments, only: [:create, :destroy, :show]
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
    end
  end

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :topic
  attr_accessible :body, :title, :topic, :image

  after_create :create_vote

  mount_uploader :image, ImageUploader

  def up_votes
    self.votes.where(value: 1).count
  end

  def down_votes
    self.votes.where(value: -1).count
  end  

  def points
    self.votes.sum(:value).to_i
  end

  def update_rank
    age = (self.created_at - Time.new(1970,1,1)) / 86400
    new_rank = points + age

    self.update_attribute(:rank, new_rank)
  end

  default_scope order('rank DESC')
  scope :visible_to, lambda { |user| user ? scoped : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  private

  # Who ever created a post, should automatically be set to "voting" it up.
  def create_vote
    user.votes.create(value: 1, post: self)
  end  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :name, :public
  has_many :posts, dependent: :destroy

  scope :visible_to, lambda { |user| user ? scoped : where(public: true) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
     @posts = Post.visible_to(current_user).where("posts.created_at > ?",7.days.ago).paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController

  def show
    @topic = Topic.find(params[:topic_id])
    authorize! :read, @topic, message: "You need to be signed-in to do that."
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize! :create, Post, message: "You need to be a member to create a post. Thanks!"
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params[:post])
    @post.topic = @topic
    authorize! :create, @post, message: "You need to be signed up to do that."
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :edit, @post, message: "You need to own the post to edit it."
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :update, @post, message: "You need to own the post to edit it."
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

   def destroy
     @topic = Topic.find(params[:topic_id])
     @post = Post.find(params[:id])

     title = @post.title
     authorize! :destroy, @post, message: "You need to own the post to delete it."
      if @post.destroy
        flash[:notice] = "\"#{title}\" was deleted successfully."
        redirect_to @topic
      else
        flash[:error] = "There was an error deleting the post."
        render :show
      end
    end  
  end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
  end

  def new
    @topic = Topic.new
    authorize! :create, @topic, message: "You need to be an admin to do that. Thanks!"
  end

  def show
    @topic = Topic.find(params[:id])
    authorize! :read, @topic, message: "You need to be signed-in to do that."
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to be an admin to do that. Thanks!"
  end

  def create
    @topic = Topic.new(params[:topic])
    authorize! :create, @topic, message: "You need to be an admin to do that. Thanks!"
    if @topic.save
      flash[:notice] = "Topic was saved successfully."
      redirect_to @topic
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    authorize! :update, @topic, message: "You need to own a topic to update it. Thanks!"
    if @topic.update_attributes(params[:topic])
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again"
      render :edit
    end
  end
  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name
    authorize! :destory, @topic, message: "You need to own that topic to delete it."
    if @topic.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/posts/_form.html.erb
<%= form_for [topic, post], html: { class: 'form-horizontal' } do |f| %>
<% if post.errors.any? %>
    <div class="alert alert-block">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <%= control_group_tag(post.errors[:title]) do %>
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  <% end %>
  <%= control_group_tag(post.errors[:body]) do %>
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, rows: 8 %>
    </div>
  <% end %>
  <%= control_group_tag(post.errors[:image]) do %>
     <%= f.label :image, class: 'control-label' %>
     <div class="controls">
        <%= f.file_field :image %>
     </div>
     <% end %>
     <br>
     <br>
     <div class="control-group">
      <div class="controls">
     <%= f.submit "Save", class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/topics/posts/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="span-6">
    <p>Guidelines for new topic:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span-6">
    <%= form_for @topic, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :name, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :description, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :description, rows: 8 %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public topic
          <% end %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="span4">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span8">
     <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/topics/posts/show.html.erb
<div class="row">
  <div class="span8">
    <small>
      <%= render partial: 'votes/voter', locals: { topic: @topic, post: @post } %>
      <h1><%= markdown @post.title %></h1>
      <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by 
      <%= @post.user.name %>
    </small>
    <p><%= markdown @post.body %></p>
    <p><%= image_tag(@post.image_url) if @post.image? %>
  </div>
  <h1>Comments</h1>
  There are <%= @comments.count %> comments.
  <h2 class='js-comments-count'><%= @comments.count %> Comments</h2>

  <div class="js-comments">
    <%= render partial: "comments/comment", collection: @comments %>
  </div>

  <a href="#" class="js-show-hide" data-selector="js-new-comment">Add Comment</a>

  <div class="js-new-comment hide">
    
  <h1>New Comment</h1>
  <!-- put the form below into a partial: comments/form -->
  
  <%= render partial: "comments/form", locals: { topic: @topic, post: @post, comment: @comment } %>

  <%= render partial: "form", locals: { topic: @topic, post: @post, comment: @comment } %>
  
  <div class="span4">
    <% if can? :edit, @post %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-large btn-block' %>
    <% end %>
    <% if can? :destroy, @post %>
      <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-large btn-block btn-danger', confirm: 'Are you sure you want to delete this post?' %>
    <% end %> 
    <div>
      <h3><%= pluralize(@post.points, 'point') %></h3>
      <small>
        <%= pluralize(@post.up_votes, 'up vote') %>, 
        <%= pluralize(@post.down_votes, 'down vote') %>
      </small>
    </div>
    <%= render partial: 'favorites/favorite', locals: { topic: @topic, post: @post } %>
  </div>
</div>