config/routes.rb
Bloccit::Application.routes.draw do

  get "posts/index"

  get "comments/new"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: [:show, :index]

  resources :posts, only: [:index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :comments, only: [:create, :destroy, :show]
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
    end
  end

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloccit</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
     <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Bloccit", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Topics", topics_path %></li>
        <li><%= link_to "Popular", posts_path %></li>
        <li><%= link_to "Users", users_path %></li>
    <div class="pull-right user-info">
        
    <% if current_user %>
      <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>

    Hello <%= link_to (current_user.name || current_user.email), current_user %>
    <%= link_to edit_user_registration_path, class: 'btn btn-mini' do %>
      <i class="icon-user"> </i>
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-mini' do %>
      <i class="icon-share-alt"> </i>
    <% end %>
        <% else %>
        <%= link_to "Sign In", new_user_session_path %> or 
        <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
    </div>

      </ul>
    <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
 <%= javascript_include_tag "application" %>
  </body>
</html>